// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBebKNpLK1IK85z-AHza7eResge1ZgYd00',
    appId: '1:487835997023:web:35109e67f1431255c7dcea',
    messagingSenderId: '487835997023',
    projectId: 'to-do-fe340',
    authDomain: 'to-do-fe340.firebaseapp.com',
    storageBucket: 'to-do-fe340.firebasestorage.app',
    measurementId: 'G-QEGPR0WHG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtZENwcL8__TJ5mJax0iPVBerxV3DlsIU',
    appId: '1:487835997023:android:7b5b925a5e4809c4c7dcea',
    messagingSenderId: '487835997023',
    projectId: 'to-do-fe340',
    storageBucket: 'to-do-fe340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0lb7qlWU4K4kMNm48UPf16hOcSpSsGBY',
    appId: '1:487835997023:ios:eb39e58f3b1762ffc7dcea',
    messagingSenderId: '487835997023',
    projectId: 'to-do-fe340',
    storageBucket: 'to-do-fe340.firebasestorage.app',
    iosBundleId: 'com.example.frontand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0lb7qlWU4K4kMNm48UPf16hOcSpSsGBY',
    appId: '1:487835997023:ios:eb39e58f3b1762ffc7dcea',
    messagingSenderId: '487835997023',
    projectId: 'to-do-fe340',
    storageBucket: 'to-do-fe340.firebasestorage.app',
    iosBundleId: 'com.example.frontand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBebKNpLK1IK85z-AHza7eResge1ZgYd00',
    appId: '1:487835997023:web:383710fbb0c43162c7dcea',
    messagingSenderId: '487835997023',
    projectId: 'to-do-fe340',
    authDomain: 'to-do-fe340.firebaseapp.com',
    storageBucket: 'to-do-fe340.firebasestorage.app',
    measurementId: 'G-02P78K8HQ4',
  );

}